name: TestCode

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  rspec-job:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1

      - name: Setup Ruby 2.7.2
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          #bundle exec danger
          bundle exec rspec
